### ISSUE TITLE
no module setuptools or extern

### ISSUE THREAD

**Issue by sure0000** [oncecloud/vStack#5]
# 原因：缺少python相应的模块
# 解决方法
### 下载setuotools包
> wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz

### 解压
> tar zxvf setuotools-0.6c11.tar.gz

### 编译setuptools
> cd 0.6c11.tar.gz
> python setup.py build 

### 安装setuptools
> python srtup.py install

## 缺少extern及其他python模块的解决方法与上面相同

**Comment by SnailJie** [comment]
这个与个人的python环境相关，不属于项目本身的问题。编译时间那个问题可以作为一个issue ^_ ^
